### ISSUE TITLE
Autofill Form Plug-in Settings Screens Issue & Suggestion

### ISSUE THREAD

**Issue by kenreeser** [sarahavilov/Autofill-Forms#6]
Hi Sarah,

Late last year, you and exchanged some e-mails regarding some issues I was experiencing with the Autofill Forms (AF) plug-in on the OS X version of Firefox. Specifically, I was experiencing truncated window pane issues when viewing the various "Settings" panes. I thought my issue was resolved, but later discovered it wasn't. However, I believe I've discovered a pattern that may help you resolve a potential AF plug-in bug. To that end, I've created a video (with narration track) that shows you the issue and the repeatable pattern. Also, I included a helpful suggestion for making AF even more productive.

My i-net service provider has stated I can send attachments up to 100 MBs, however they're experiencing an issue that's preventing me from sending attachments larger than 5 MBs. To that end, I've included a download link below for the video.

http://s2s.dnsalias.com:5000/fbsharing/cR5lmKgS

Regards,
Ken Reeser

**Comment by sarahavilov** [comment]
Thanks Ken for the video. I removed the link as seems like there are many personal info in the video. You can remove it from the hosting as I have already watched it.

And about these issues. They all related to the way Firefox handles complex windows. I have been playing around to fix this, but still couldn't find how. Currently, I am trying to split the settings tabs into different windows. Hopefully this will fix all these issues all together.

**Comment by kenreeser** [comment]
Hi Sara,

Thanks very much for reviewing my AutoFill Forms issue video. Also, thank you very much for tackling the window issues. I'd really like to see all the pref window content made much taller--especially the one within which you can modify profile elements.

By the way, I donated towards AutoFill Forms plug-in when I began using it a few years ago and feel it's only fair to make another donation after these windows have been adjusted. I've always been a propionate of a FireFox extension store, however, over the years, many FF extension developers told me I didn't understand the open-source concept. Because I sold large web-based applications to school districts across the nation, I understood open-source way better then they did.

Regards,
Ken Reeser


On Aug 26, 2015, at 8:45 AM, sarahavilov <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Ken for the video. I removed the link as seems like there are many personal info in the video. You can remove it from the hosting as I have already watched it.

And about these issues. They all related to the way Firefox handles complex windows. I have been playing around to fix this, but still couldn't find how. Currently, I am trying to split the settings tabs into different windows. Hopefully this will fix all these issues all together.

**Comment by sarahavilov** [comment]
Ken please try the latest dev version,
https://github.com/sarahavilov/Autofill-Forms/blob/master/aff.xpi?raw=true

Download the XPI and drop it into your FF and let me know the result.

**Comment by kenreeser** [comment]
Hi Sara,

Thanks very much. I’m just about to download and install. Also, I was just about to send you another e-mail regarding the latest AutoFill Forms update (updated yesterday I believe). For some reason one of our sites upon which we file patient claims, doesn’t work correctly anymore when fill out the data. This has been working correctly for the last couple of years. Now, some of the fields at the bottom of a certain page will populate, but then disappear. Any ideas? I’ll try this new version, but may have to downgrade the version prior to the update this week.

Regards,
Ken Reeser

On Aug 26, 2015, at 10:17 AM, sarahavilov <notifications@github.com<mailto:notifications@github.com>> wrote:


Ken please try the latest dev version,
https://github.com/sarahavilov/Autofill-Forms/blob/master/aff.xpi?raw=true

Download the XPI and drop it into your FF and let me know the result.

**Comment by kenreeser** [comment]
Hi Sara,

I just installed and opened the pref windows—FANTASTIC!!!!! Thank you very much, this is what’s been needed for a looooong time. However, one minor issue: I can access all the fields within each pref screen, however, I cannot scroll up or down.

Regards,
Ken Reeser

On Aug 26, 2015, at 10:17 AM, sarahavilov <notifications@github.com<mailto:notifications@github.com>> wrote:


Ken please try the latest dev version,
https://github.com/sarahavilov/Autofill-Forms/blob/master/aff.xpi?raw=true

Download the XPI and drop it into your FF and let me know the result.

**Comment by sarahavilov** [comment]
> I can access all the fields within each pref screen, however, I cannot scroll up or down.

Well, if you resize the window, you will need to switch to another tab and then the scroll issue should have been fixed (at least this is how it works for me on my Mac). Actually the "prefWindow" has a very old bug in Mac version that is responsible for all these troubles. There is no fix for this as far as I know.

> Now, some of the fields at the bottom of a certain page will populate, but then disappear. Any ideas?

In the new release, I had to change the way AutoFill fills the forms to be compatible with the upcoming e10s changes. Have no idea what could be the problem here! See if you can reproduce this on a simple page. If so please open a new bug.

**Comment by kenreeser** [comment]
Hi Sara,

A bit more observations: Do you remember in my video how the profiles that contained a small number of rules (typically less than approximately 30 rules), when selected, would cause the windows to collapse when switching between them? Well, now instead of making the window collapse, when I select a profile with less than 30 rules, I can scroll without having to change windows. But, if I select one of my patient profiles (much more than 30 rules), I cannot scroll. Also, when the “Main” or “Profiles” panes are selected prior to closing the prefs window, those panes are displayed as collapsed the next time you open the prefs window (unless I selected another pane and then reselect the one I was viewing).

Regards,
Ken Reeser

Begin forwarded message:

**Comment by kenreeser** [comment]
Could you please send me an .xpi of the version of AutoFill Forms just prior to the update earlier this week? I just want to see if my new issue was caused by changes to the site or the plug-in.

Thx,
Ken Reeser

**Comment by sarahavilov** [comment]
https://addons.mozilla.org/en-US/firefox/addon/autofill-forms/versions/

**Comment by kenreeser** [comment]
Well, it looks like your update isn’t what caused the issue below (prior message below) on one of our claims filling sites. It looks like these idiots made some type of change which has now rendered a portion of the automation provided by AutoFill Forms useless. Argh!

Ken Reeser

Begin forwarded message:

**Comment by kenreeser** [comment]
Hi Sara,

In a prior e-mail I indicated my issue below was caused by the site developer. Well, after more testing, I found beyond a doubt, the issue is caused by whatever you added to version 1.0.5—version 1.0.4 will properly fill out all fields on the our patient’s insurance company’s claim filing site, while version 1.0.5 will fill out all fields except a group at the bottom. Perhaps more iFrame work is required, or you could make using iFrames a preference checkbox? I’d like to be able to have access to the window changes you made, but it’s more important that I be able to automatically fill out all fields that were saved as part of a profile—especially if the prior version worked. I’ll try to create a video of my issue and send you a link.

Regards,
Ken Reeser

On Aug 26, 2015, at 10:33 AM, Ken <ken@reesers.us<mailto:ken@reesers.us>> wrote:

Hi Sara,

Thanks very much. I’m just about to download and install. Also, I was just about to send you another e-mail regarding the latest AutoFill Forms update (updated yesterday I believe). For some reason one of our sites upon which we file patient claims, doesn’t work correctly anymore when fill out the data. This has been working correctly for the last couple of years. Now, some of the fields at the bottom of a certain page will populate, but then disappear. Any ideas? I’ll try this new version, but may have to downgrade the version prior to the update this week.

Regards,
Ken Reeser

On Aug 26, 2015, at 10:17 AM, sarahavilov <notifications@github.com<mailto:notifications@github.com>> wrote:


Ken please try the latest dev version,
https://github.com/sarahavilov/Autofill-Forms/blob/master/aff.xpi?raw=true

Download the XPI and drop it into your FF and let me know the result.

**Comment by kenreeser** [comment]
Hi Sara,

Please find the attached video link below that describes the issue I’m experiencing with AutoFill Forms 1.0.5. This issue does not occur in version 1.0.4.

http://s2s.dnsalias.com:5000/fbsharing/q0qxcvKF


Best,
Ken Reeser



Hi Sara,

In a prior e-mail I indicated my issue below was caused by the site developer. Well, after more testing, I found beyond a doubt, the issue is caused by whatever you added to version 1.0.5—version 1.0.4 will properly fill out all fields on the our patient’s insurance company’s claim filing site, while version 1.0.5 will fill out all fields except a group at the bottom. Perhaps more iFrame work is required, or you could make using iFrames a preference checkbox? I’d like to be able to have access to the window changes you made, but it’s more important that I be able to automatically fill out all fields that were saved as part of a profile—especially if the prior version worked. I’ll try to create a video of my issue and send you a link.

Regards,
Ken Reeser

On Aug 26, 2015, at 10:33 AM, Ken <ken@reesers.us<mailto:ken@reesers.us>> wrote:

Hi Sara,

Thanks very much. I’m just about to download and install. Also, I was just about to send you another e-mail regarding the latest AutoFill Forms update (updated yesterday I believe). For some reason one of our sites upon which we file patient claims, doesn’t work correctly anymore when fill out the data. This has been working correctly for the last couple of years. Now, some of the fields at the bottom of a certain page will populate, but then disappear. Any ideas? I’ll try this new version, but may have to downgrade the version prior to the update this week.

Regards,
Ken Reeser

On Aug 26, 2015, at 10:17 AM, sarahavilov <notifications@github.com<mailto:notifications@github.com>> wrote:


Ken please try the latest dev version,
https://github.com/sarahavilov/Autofill-Forms/blob/master/aff.xpi?raw=true

Download the XPI and drop it into your FF and let me know the result.

**Comment by kenreeser** [comment]
Sara,

Are you receiving my e-mails in this manner? See thread below for my last 2 messages if not:



Hi Sara,

Please find the attached video link below that describes the issue I’m experiencing with AutoFill Forms 1.0.5. This issue does not occur in version 1.0.4.

http://s2s.dnsalias.com:5000/fbsharing/q0qxcvKF


Best,
Ken Reeser



Hi Sara,

In a prior e-mail I indicated my issue below was caused by the site developer. Well, after more testing, I found beyond a doubt, the issue is caused by whatever you added to version 1.0.5—version 1.0.4 will properly fill out all fields on the our patient’s insurance company’s claim filing site, while version 1.0.5 will fill out all fields except a group at the bottom. Perhaps more iFrame work is required, or you could make using iFrames a preference checkbox? I’d like to be able to have access to the window changes you made, but it’s more important that I be able to automatically fill out all fields that were saved as part of a profile—especially if the prior version worked. I’ll try to create a video of my issue and send you a link.

Regards,
Ken Reeser

On Aug 26, 2015, at 10:33 AM, Ken <ken@reesers.us<mailto:ken@reesers.us>> wrote:

Hi Sara,

Thanks very much. I’m just about to download and install. Also, I was just about to send you another e-mail regarding the latest AutoFill Forms update (updated yesterday I believe). For some reason one of our sites upon which we file patient claims, doesn’t work correctly anymore when fill out the data. This has been working correctly for the last couple of years. Now, some of the fields at the bottom of a certain page will populate, but then disappear. Any ideas? I’ll try this new version, but may have to downgrade the version prior to the update this week.

Regards,
Ken Reeser

On Aug 26, 2015, at 10:17 AM, sarahavilov <notifications@github.com<mailto:notifications@github.com>> wrote:


Ken please try the latest dev version,
https://github.com/sarahavilov/Autofill-Forms/blob/master/aff.xpi?raw=true

Download the XPI and drop it into your FF and let me know the result.

**Comment by kenreeser** [comment]
Sara,

Are you receiving my e-mails in this manner (i.e. replies to your messages through Git Hub? See thread below for my last 2 messages if not:



Hi Sara,

Please find the attached video link below that describes the issue I’m experiencing with AutoFill Forms 1.0.5. This issue does not occur in version 1.0.4.

http://s2s.dnsalias.com:5000/fbsharing/q0qxcvKF


Best,
Ken Reeser



Hi Sara,

In a prior e-mail I indicated my issue below was caused by the site developer. Well, after more testing, I found beyond a doubt, the issue is caused by whatever you added to version 1.0.5—version 1.0.4 will properly fill out all fields on the our patient’s insurance company’s claim filing site, while version 1.0.5 will fill out all fields except a group at the bottom. Perhaps more iFrame work is required, or you could make using iFrames a preference checkbox? I’d like to be able to have access to the window changes you made, but it’s more important that I be able to automatically fill out all fields that were saved as part of a profile—especially if the prior version worked. I’ll try to create a video of my issue and send you a link.

Regards,
Ken Reeser

On Aug 26, 2015, at 10:33 AM, Ken <ken@reesers.us<mailto:ken@reesers.us>> wrote:

Hi Sara,

Thanks very much. I’m just about to download and install. Also, I was just about to send you another e-mail regarding the latest AutoFill Forms update (updated yesterday I believe). For some reason one of our sites upon which we file patient claims, doesn’t work correctly anymore when fill out the data. This has been working correctly for the last couple of years. Now, some of the fields at the bottom of a certain page will populate, but then disappear. Any ideas? I’ll try this new version, but may have to downgrade the version prior to the update this week.

Regards,
Ken Reeser

On Aug 26, 2015, at 10:17 AM, sarahavilov <notifications@github.com<mailto:notifications@github.com>> wrote:


Ken please try the latest dev version,
https://github.com/sarahavilov/Autofill-Forms/blob/master/aff.xpi?raw=true

Download the XPI and drop it into your FF and let me know the result.

**Comment by sarahavilov** [comment]
Well, its really hard to say why the values are disappearing. I was hoping you could regenerate the bug on a simple form.

Anyhow, I pushed a new version here that might help,
https://github.com/sarahavilov/Autofill-Forms/blob/master/aff.xpi?raw=true

Try this version and let me know the result

**Comment by kenreeser** [comment]
Hi Sara,

I really appreciate you trying to resolve the disappearing data issue I’m currently experiencing with the latest version of AutoFill Forms and the Availity.com<http://Availity.com> site. I tried the latest version and I’m still experiencing this issue. I wish I could reproduce this issue on a simple form as well, but out of all insurance/payer sites upon which we submit patient claims, Availity.com<http://Availity.com> is the only one exhibiting the disappearing data issue. I need to submit a number of patient claims today and will continue to use the new version to re-confirm whether other sites exhibit the same issue.

Also, I finally have a definitive pattern regarding AF’s settings window issues (i.e. the temporary scroll.no<http://scroll.no>-scroll & window content size issues)—at least on the OS X version of FF & AF. If I ensure to close AF’s settings screen with any pane selected except, “Simple”, then the next time I open the settings window, the scrolling issue disappears. In addition, if I close AF’s settings window set to either the “Advanced” or “Interface” pane, then I can view the “Profile” or “Main” panes without having to toggle-click to fix the window size. So, for now, the best AF settings window use work-around is to tell users to set their AF settings pane to “Advanced” or “Interface” prior to closing the window.

Regards,
Ken Reeser

On Sep 16, 2015, at 7:41 AM, sarahavilov <notifications@github.com<mailto:notifications@github.com>> wrote:


Well, its really hard to say why the values are disappearing. I was hoping you could regenerate the bug on a simple form.

Anyhow, I pushed a new version here that might help,
https://github.com/sarahavilov/Autofill-Forms/blob/master/aff.xpi?raw=true

Try this version and let me know the result

**Comment by sarahavilov** [comment]
Hi Ken,
AF’s settings window issues are Mac only. To me this is the best we can get for now.

Regarding the data disappearance, I need to somehow be able to regenerate this. By releasing e10s you are not be able to use the old version of AutoFill anymore. So I guess we need to fix the latest release.

**Comment by kenreeser** [comment]
I can use the old version (1.0.4), but I lose the window size fix. Would it be helpful to send a video of the actual data disappearance? I know I sent a video, but I described what happens instead of showing it.

Regards,
Ken Reeser

On Sep 21, 2015, at 2:43 AM, sarahavilov <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Ken,
AF’s settings window issues are Mac only. To me this is the best we can get for now.

Regarding the data disappearance, I need to somehow be able to regenerate this. By releasing e10s you are not be able to use the old version of AutoFill anymore. So I guess we need to fix the latest release.

**Comment by sarahavilov** [comment]
No you cannot really use the older versions anymore. They are not going to be compatible with FF 45. We need to somehow fix the latest version. Please try to regenerate the bug in a simpler form so that I could be able to see and fix the bug.

**Comment by kenreeser** [comment]
Well, it if comes 2 having 2 chose between my excellent client billing workflow based upon Autofill Form and upgrading to FF 45, I’ll chose the workflow and stay with version 41 (or below 45). Would it be much work for you to make those window size fixes to version 1.0.4? Because that version works perfect aside from not having the wonderful window fixes. Also, we use at least 8 different insurance claim filing sites and only one of them has the issue we’ve discussed. To that end, it’s going 2 b like looking 4 needle in a haystack trying to locate another (and simpler/non-proprietary) site that also exhibits this issue.

Regards,
Ken Reeser


On Oct 6, 2015, at 9:26 AM, sarahavilov <notifications@github.com<mailto:notifications@github.com>> wrote:


No you cannot really use the older versions anymore. They are not going to be compatible with FF 45. We need to somehow fix the latest version. Please try to regenerate the bug in a simpler form so that I could be able to see and fix the bug.
